version: "3.1"

services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 9080:8080
      
  db:
    image: mysql:8.0.24
    restart: always
    environment:
      MYSQL_DATABASE: 'db_prueba'
      MYSQL_USER: 'miguel1121'
      MYSQL_PASSWORD: '123456789'
      MYSQL_ROOT_PASSWORD: 'qwertyuiop'
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - ./db_prueba:/var/lib/mysql
      - ./db-scripts/:/docker-entrypoint-initdb.d/
    command: --default-authentication-plugin=mysql_native_password
volumes:
  db_prueba:
