DROP TABLE IF EXISTS USUARIO;

CREATE TABLE USUARIO (
  usuario_id  INT PRIMARY KEY,
  username VARCHAR(250) NOT NULL,
  nombre VARCHAR(250) NOT NULL,
  apellido VARCHAR(250) NOT NULL,
  email VARCHAR(250) NOT NULL,
  password VARCHAR(250) NOT NULL
);