DROP TABLE IF EXISTS db_prueba.USUARIO;

CREATE TABLE db_prueba.USUARIO (
  usuario_id  INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  username VARCHAR(250) NOT NULL,
  nombre VARCHAR(250) NOT NULL,
  apellido VARCHAR(250) NOT NULL,
  email VARCHAR(250) NOT NULL,
  password VARCHAR(250) NOT NULL
);
